name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to AWS ECR
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_REGISTRY_URL }}

    - name: Build Docker image
      run: |
        cd python-app
        docker build -t awsapp -f Dockerfile .

    - name: Tag Docker Image (latest)
      run: docker tag awsapp:latest ${{ secrets.AWS_REGISTRY_URL }}/awsapp:latest

    - name: Tag Docker Image (with Branch and Commit)
      run: |
        BRANCH=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
        COMMIT_SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker tag awsapp:latest ${{ secrets.AWS_REGISTRY_URL }}/awsapp:$BRANCH-$COMMIT_SHORT_SHA

    - name: Debug variables
      run: |
        echo "Branch: $BRANCH"
        echo "Commit Short SHA: $COMMIT_SHORT_SHA"

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.AWS_REGISTRY_URL }}/awsapp:latest
        docker push ${{ secrets.AWS_REGISTRY_URL }}/awsapp:$BRANCH-$COMMIT_SHORT_SHA
